### ISSUE TITLE
Build steps for jswhois don't work out of the box for jswhois executable

### ISSUE THREAD

**Issue by andrewferrier** [jschauma/jswhois#1]
Great work on `jswhois`, nice tool. Thanks!

It looks like a built copy of the `jswhois` executable has been checked into git. This means that cloning this repo and running `make install` does not work for me and anyone not using a Mac (I think), as this executable is not rebuilt.

Contrary to the instructions in the README, I had to run `make clean` first to delete and force it to be rebuilt.

I think it would be great to make that clearer. It works fine on Linux otherwise for me. I would suggest perhaps you don't want to check in the built program at all? That might be something better off `.gitignore`d, or added as a GitHub release.

**Comment by jschauma** [comment]
You're right - that binary should not have been imported. Thanks for letting me know!
